import json
from datetime import timedelta


def format_time(seconds: float) -> str:
    td = timedelta(seconds=seconds)
    total_seconds = int(td.total_seconds())
    hours = total_seconds // 3600
    minutes = (total_seconds % 3600) // 60
    secs = total_seconds % 60
    ms = int((seconds - int(seconds)) * 100)
    if hours > 0:
        return f"{hours:02d}:{minutes:02d}:{secs:02d}.{ms:02d}"
    return f"{minutes:02d}:{secs:02d}.{ms:02d}"


def export_timeline(selections: list, output_path: str) -> str:
    """
    Export a plain-text timeline instruction file.
    selections: [{timestamp, filename, duration, search_query, text}, ...]
    """
    lines = [
        "B-ROLL TIMELINE EXPORT",
        "Generated by B-Roll Assistant",
        "=" * 50,
        "",
        "TIMELINE INSTRUCTIONS:",
        "",
    ]

    for i, item in enumerate(selections, 1):
        ts = item.get("timestamp", 0)
        filename = item.get("filename", "unknown.mp4")
        duration = item.get("duration", 3)
        text = item.get("text", "")
        query = item.get("search_query", "")

        lines.append(f"[{i}] {format_time(ts)} → {filename}")
        lines.append(f"     Duration: {duration}s")
        lines.append(f"     Context: {text}")
        lines.append(f"     Search: {query}")
        lines.append("")

    lines += [
        "=" * 50,
        "IMPORT INSTRUCTIONS:",
        "",
        "Premiere Pro / DaVinci Resolve:",
        "  1. Import all downloaded clips into your media bin",
        "  2. Place your main video on track V1",
        "  3. Add B-roll clips on track V2 at the timestamps above",
        "  4. Adjust clip positions as needed",
        "",
        "Final Cut Pro:",
        "  1. Import clips into library",
        "  2. Use Connected Clips above the primary storyline",
        "  3. Snap clips to the timecodes listed above",
    ]

    with open(output_path, "w") as f:
        f.write("\n".join(lines))

    return output_path
